#Twitter Consumer Keys and Access Tokens
ACCESS_TOKEN = "800897753085833216-D4vvTh6tpTx6JBlfiKkVzCplYt9GNMf"
ACCESS_TOKEN_SECRET = "JIe91vgWJHxYhgbCLc4wQpyOXHfypp563B1r7o9kSBWaw"
CONSUMER_KEY = "wzVCFEmNrAeUYl37W0QKENlRG"
CONSUMER_KEY_SECRET = "rZGlvs4TrpiKKHabTrJVrqziDnS1tirtMrQfCyctNpjTErNe7a"

def getKeys():
	return (ACCESS_TOKEN, ACCESS_TOKEN_SECRET, CONSUMER_KEY, CONSUMER_KEY_SECRET)